version: '3' # specify docker-compose version

volumes:
  # Set up with `docker volume create ...`. See docker README for more info
  data_volume:
    external: true

services:
  # Runs from the latest release
  matrix-reminder-bot:
    image: anoa/matrix-reminder-bot
    volumes:
      - data_volume:/data
    extra_hosts:
      - "dockerhost:192.168.42.245"

  # Builds and runs from local code
  matrix-reminder-bot-local-checkout:
    build:
      context: .
      dockerfile: docker/Dockerfile
      # Build arguments may be specified here
      # args:
      #  PYTHON_VERSION: 3.8
    volumes:
      - data_volume:/data
    extra_hosts:
      - "dockerhost:192.168.42.245"
