# This workflow will install Python dependencies, then lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U isort==5.0.4 flake8==3.8.3 flake8-comprehensions==3.2.3 black==19.10b0

    - name: Check import statement sorting
      run: |
        isort -c --df matrix_reminder_bot matrix-reminder-bot

    - name: Python syntax errors, undefined names, etc.
      run: |
        flake8 . --count --show-source --statistics

    - name: PEP8 formatting
      run: |
        black --check --diff matrix_reminder_bot/ matrix-reminder-bot
